Add jobs to the docker push images procedure workflow file

diff --git a/.github/workflows/Procedure_push_docker_images.yml b/.github/workflows/Procedure_push_docker_images.yml
--- a/.github/workflows/Procedure_push_docker_images.yml
+++ b/.github/workflows/Procedure_push_docker_images.yml
@@ -1,4 +1,3 @@
-
 run-name: Launch Push Docker Images - Executed by @${{ github.actor }}
 name: Push Docker Images
 
@@ -32,3 +31,50 @@ on:
         required: true
         type: boolean
         default: true
+
+jobs:
+  build-and-push:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ inputs.DOCKER_REFERENCE }}
+
+    - name: Log in to Docker Hub
+      uses: docker/login-action@v3
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+
+    - name: Build Wazuh images
+      run: |
+        IMAGE_TAG=${{ inputs.IMAGE_TAG }}
+        FILEBEAT_MODULE_VERSION=${{ inputs.FILEBEAT_MODULE_VERSION }}
+        REVISION=${{ inputs.REVISION }}
+        PUSH_IMAGES=${{ inputs.PUSH_IMAGES }}
+
+        if [[ "$IMAGE_TAG" == *"-"* ]]; then
+          IFS='-' read -r -a tokens <<< "$IMAGE_TAG"
+          if [ -z "${tokens[1]}" ]; then
+            echo "Invalid image tag: $IMAGE_TAG"
+            exit 1
+          fi
+          DEV_STAGE=${tokens[1]}
+          WAZUH_VER=${tokens[0]}
+          ./build-docker-images/build-images.sh -v $WAZUH_VER -r $REVISION -d $DEV_STAGE -f $FILEBEAT_MODULE_VERSION
+        else
+          ./build-docker-images/build-images.sh -v $IMAGE_TAG -r $REVISION -f $FILEBEAT_MODULE_VERSION
+        fi
+
+    - name: Tag and Push Wazuh images
+      if: ${{ inputs.PUSH_IMAGES == 'true' }}
+      run: |
+        IMAGE_TAG=${{ inputs.IMAGE_TAG }}
+        IMAGE_NAMES=${{ inputs.IMAGE_NAMES }}
+        IFS=',' read -r -a images <<< "$IMAGE_NAMES"
+        for image in "${images[@]}"; do
+          docker tag wazuh/$image:${WAZUH_VERSION} wazuh/$image:$IMAGE_TAG
+          docker push wazuh/$image:$IMAGE_TAG
+        done
